repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.3
  hooks:
    - id: ruff
      name: lint with ruff
    - id: ruff
      name: sort imports with ruff
      args: [--select, I, --fix]
    - id: ruff-format
      name: format with ruff
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.2
  hooks:
    - id: codespell
      additional_dependencies:
        - tomli