[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "fit_changedetector"
dynamic = ["version"]
readme = "README.md"
authors = [
  {name="Simon Norris", email="snorris@hillcrestgeo.ca"},
]
description = "Compare geo-data, report on diffs"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: GIS",
    "Operating System :: OS Independent"
]
dependencies = [
  "click",
  "cligj",
  "geopandas>=1.0.0",
  "pyarrow",
]

[project.optional-dependencies]
test = [
  "pytest",
  "build",
  "pre-commit"
]

[project.scripts]
changedetector = "fit_changedetector.cli:cli"

[project.urls]
Homepage = "https://github.com/bcgov/fit_changedetector"
Issues = "https://github.com/bcgov/fit_changedetector"

[tool.setuptools_scm]
write_to = "src/fit_changedetector/_version.py"

[tool.ruff]
line-length = 88