"""Regenerate the CLI --help block in README.md from the live CLI.

Run automatically by pre-commit; can also be run manually:
    uv run python scripts/update_cli_docs.py
"""

import re
import sys
from pathlib import Path

from click.testing import CliRunner

from fit_changedetector.cli import cli

README = Path(__file__).resolve().parent.parent / "README.md"
START = "<!-- BEGIN CLI HELP (auto-generated by scripts/update_cli_docs.py - do not edit by hand) -->"
END = "<!-- END CLI HELP -->"


def _help_block(args, prompt):
    result = CliRunner().invoke(cli, [*args, "--help"], prog_name="changedetector")
    lines = [f"    $ {prompt}"]
    lines += [f"    {line}" if line else "" for line in result.output.splitlines()]
    return "\n".join(lines)


def generate():
    # auto-discover subcommands rather than hardcoding them, so a new command
    # is documented automatically instead of silently missing from the README
    blocks = [_help_block([], "changedetector --help")]
    for name in sorted(cli.commands):
        blocks.append(_help_block([name], f"changedetector {name} --help"))
    return "\n\n".join(blocks)


def main():
    content = README.read_text()
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(content):
        raise SystemExit(f"README.md is missing the {START} / {END} markers")
    new_content = pattern.sub(f"{START}\n{generate()}\n{END}", content)
    if new_content == content:
        return 0
    README.write_text(new_content)
    print("README.md CLI help block was out of date and has been regenerated.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
