name: Test
on:
  push:
    branches: [ main]
    paths:
      - '.github/workflows/test.yaml'
      - 'requirements*.txt'
      - 'src/fit_changedetector/**'
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yaml'
      - 'requirements*.txt'
      - 'src/fit_changedetector/**'
      - 'tests/**'
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    container: ghcr.io/osgeo/gdal:ubuntu-small-${{ matrix.gdal-version }}
    env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.9'
            gdal-version: '3.7.3'
          - python-version: '3.12'
            gdal-version: '3.9.2'
    steps:
      - uses: actions/checkout@v4.1.3

      - name: Update
        run: |
          apt-get update
          apt-get -y install software-properties-common
          add-apt-repository -y ppa:deadsnakes/ppa
          apt-get update

      - name: Set up Python ${{ matrix.python-version }}
        run: |
          apt-get install -y --no-install-recommends \
            python${{ matrix.python-version }} \
            python${{ matrix.python-version }}-dev \
            python${{ matrix.python-version }}-venv \
            python3-pip \
            g++

      - name: Install dependencies
        run: |
          python${{ matrix.python-version }} -m venv testenv
          . testenv/bin/activate
          python -m pip install --upgrade pip
          python -m pip wheel -r requirements-dev.txt
          python -m pip install -r requirements-dev.txt
          python setup.py clean
          python -m pip install --no-deps --force-reinstall -e .[test]

      - name: Run tests
        run: |
          . testenv/bin/activate
          python -m pytest -v -rxXs