@echo off
:: Install the fit_changedetector wheel into the conda environment.
for /f "delims=" %%i in ('dir /b "%PREFIX%\fit_changedetector-*.whl" 2^>nul') do (
    "%PREFIX%\python" -m pip install --no-deps --quiet "%PREFIX%\%%i"
)

:: Write a desktop shortcut with the install prefix baked in.
:: PATH is set before launching so changedetector.exe is found without relying on the user's PATH.
set SHORTCUT=%USERPROFILE%\Desktop\FIT ChangeDetector.vbs
(
    echo ' FIT ChangeDetector GUI launcher — generated by installer.
    echo Dim shell
    echo Set shell = CreateObject^("WScript.Shell"^)
    echo shell.Environment^("Process"^)^("PATH"^) = "%PREFIX%\Scripts;%PREFIX%\Library\bin;%PREFIX%\Library\mingw-w64\bin;%PREFIX%\Library\usr\bin;%PREFIX%;" ^& shell.Environment^("Process"^)^("PATH"^)
    echo shell.Run """" ^& "%PREFIX%\pythonw.exe" ^& """ """ ^& "%PREFIX%\Lib\site-packages\fit_changedetector\gui.py" ^& """", 0, False
    echo Set shell = Nothing
) > "%SHORTCUT%"
